### ISSUE TITLE
Question: How does SparkContextProvider know the Spark master URL of the Spark pods on OpenShift

### ISSUE THREAD

**Issue by reynoldsm88** [radanalyticsio/spring-sparkpi#6]
I don't see in the properties files or the SparkPiProperties where it gets all the connection information for running the job on Spark.

**Comment by elmiko** [comment]
sorry @reynoldsm88 , just saw this question.

the oshinko-s2i tooling will inject the master address into the spark-submit command that is run for this app. so, it doesn't come from the properties file but directly from the command line.

i'm gonna close this question, thanks for bringing it up =)
